### ISSUE TITLE
Proxies are filtered out when using a custom resource.

### ISSUE THREAD

**Issue by colossatr0n** [JaredLGillespie/proxyscrape#14]
I may be using resources and resource types incorrectly, but I've looked through the code and think there might be an issue with `get_proxyscrape_resource` and custom resource types filtering out the proxies retrieved from `get_proxyscrape_resource`.

Example:
```
# Create proxyscrape api resource
api_resource = get_proxyscrape_resource(proxytype='http', timeout=5000, ssl='yes', anonymity='all', country='us')

# Add api resource to new resource type
add_resource_type("api", api_resource)

# Create collector
api_collector = create_collector('api-collector', 'api')

# Get proxies
api_collector.get_proxy()
```

The code above will return `None`, since `get_proxy()` applies "api" as a `type` filter, and the `type` applied to each proxy is set by the `proxytype` (which is different than the custom "api" resource type). 

It seems to me that `get_proxyscrape_resource` should have an additional `type` parameter separate from `proxytype` so that it can be used by a custom resource.

An updated usage would look like this:
```
# Create proxyscrape api resource and specify the type.
api_resource = get_proxyscrape_resource(type='api', proxytype='http', timeout=5000, ssl='yes', anonymity='all', country='us')

# Add api resource to new resource type. This resource will filter out any proxies that don't
# have type "api".
add_resource_type("api", api_resource)

# Create collector.
# Since all proxies instantiated by get_proxyscrape_resource will have the type "api", they 
# won't be filtered out by the new resource type which has the same type.
api_collector = create_collector('api-collector', 'api')

# Get proxies. The type "api" is used to filter out proxies that don't have the type "api".
api_collector.get_proxy()
```

Am I missing something here? This seems like a major functionality flaw that also leaks into other places.

**Comment by JaredLGillespie** [comment]
You're correct that there seems to be a :bug: regarding the resource type. The offending line is `self._filter_opts = {'type': self._resource_types.copy()}` which occurs in the `Collector.__init__` function.

The name of the resource_type being _api_ "should" just be a unique name for the resource type. I believe the tie between resource type names and the type filter may have been due to some resources supplying proxies with multiple types. i.e. a resource may give http and socks4 but you only want http. This can be resolved with a simple filter but was most likely added implicitly to prevent having to manually add the filter.

I'll look more into it a proper way to resolve this issue; but it may be best to remove the implicit filter (i.e. `self._filter_opts = {'type': self._resource_types.copy()}` -> `self._filter_opts = {}`).

**Comment by JaredLGillespie** [comment]
This should now be fixed.

The method usage should all be the same. The only thing that is changed is the implicit filtering based on the resource_type name is now removed. This should only affect the default resource_types ('http', 'https', 'socks4', 'socks5').

'https' for example can pull in proxies that are only 'http' and should be filtered explicitly for 'https' if those are only desired.
